remove respondd data which is not mesh relevant
freifunk-gluon/gluon pull request #1512
Opened 2018-08-11 11:02 UTC by genofire

Those data should not be provided by mesh protocol packages.
(Most of them is duplicated)

Maybe by https://github.com/freifunk-gluon/packages/pull/188

2018-08-11 11:25 UTC, NeoRaider commented
Also, when the providers are unified, the current data format generated by the batadv provider should be preserved for compatiblity.

2018-08-11 14:30 UTC, genofire commented
okay at first only the wifi clients?

2018-08-17 08:54 UTC, genofire commented
Thats what i am working on https://github.com/freifunk-gluon/packages/pull/188

2018-08-17 09:02 UTC, genofire commented
@christf current state will remove `statistics.clients.wifi` at babel - batman has it own method to count them

2018-09-29 19:01 UTC, NeoRaider commented
As mentioned in freifunk-gluon/packages#188, I think this information should be moved to the gluon-respondd package.

2019-04-10 07:57 UTC, genofire commented
Just for cleanup, in first step only: https://github.com/freifunk-gluon/packages/pull/217

enhancement comes later in: https://github.com/freifunk-gluon/packages/pull/188

2022-10-21 20:12 UTC, AiyionPrime requested changes
I think everything wifi-related has been purged from [gluon-mesh-babel](https://github.com/freifunk-gluon/gluon/tree/master/package/gluon-mesh-babel) and [gluon-mesh-batman-adv](https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-mesh-batman-adv/src/respondd.c)

@genofire Maybe you can refresh the PR to point out what I'm overlooking or close the PR to reflect it's done.

2022-10-21 20:12 UTC, AiyionPrime commented on package/gluon-mesh-batman-adv/src/respondd.c
> -static void count_iface_stations(size_t *wifi24, size_t *wifi5, const char *ifname) {
`count_iface_stations` has already been moved to respondd-neighbours.c in 0f1fa243f

2022-10-21 20:12 UTC, AiyionPrime commented on package/gluon-mesh-batman-adv/src/respondd.c
> -static void count_stations(size_t *wifi24, size_t *wifi5) {
As well as `count_stations`

2022-10-22 14:40 UTC, genofire commented
This PR is so much outdated and the subject is done.
So lets close it.

Maybe we make a new PR to remove it again, when we/i solve make that parts independent from gluon (without libgluonutils) by:

- https://github.com/freifunk-gluon/packages/pull/217
- https://github.com/freifunk-gluon/packages/pull/188

2022-10-22 14:40 UTC, closed without merging

2022-10-23 18:30 UTC, AiyionPrime commented
> This PR is so much outdated and the subject is done.
So lets close it.

What a great idea :P

But thanks for closing it, highly appreciated.