[2020.2.x] doc changes and release notes for release v2020.2.2
freifunk-gluon/gluon pull request #2151
Opened 2020-11-21 18:51 UTC by rotanid

see also #2143

2020-11-23 13:01 UTC, yanosz requested changes

2020-11-23 13:01 UTC, yanosz commented on docs/releases/v2020.2.2.rst
> +
- ath10-ct checksums are updated to address build problems

2020-11-23 20:30 UTC, blocktrron commented on docs/releases/v2020.2.2.rst
> +
ath10k-ct firmware was updated to a newer version, however we did not note this in the past.

If we want to mention the fixed built, put this to the generic notes.

2020-11-23 21:03 UTC, mweinelt commented on docs/releases/v2020.2.2.rst
> +
Mentioning firmware updates here would only make sense if people could look up a changelog if they wanted to.

In that regard, the generic "Backports of batman-adv bugfixes" is a bit too generic for my taste.

2020-11-23 21:09 UTC, rotanid commented on docs/releases/v2020.2.2.rst
> +
i'm not too fond of adding too much detail to the changelog, it's not a commit log.

also, i don't see where we fixed ath10k-ct stuff recently, aside from the discussion about whether to mention it.

2020-11-23 22:53 UTC, blocktrron commented on docs/releases/v2020.2.2.rst
> +
See https://github.com/freifunk-gluon/gluon/issues/2143#issuecomment-729763888 and my subsequent comment.

2020-11-23 23:02 UTC, rotanid commented on docs/releases/v2020.2.2.rst
> +
ah, ok. "it's not a commit log", but if other maintainers want to add it, i can live with it ;)

2020-11-25 08:38 UTC, yanosz commented on docs/releases/v2020.2.2.rst
> +
Regarding https://github.com/freifunk-gluon/gluon/issues/2143#issuecomment-731336196 the motivation is driven by CVE-2020-27638 and fixed build problems. It could help to mention those in the release notes.

2020-12-11 03:10 UTC, merged