treewide: Replace xhtml content type with html, remove xhtml workaround
freifunk-gluon/gluon pull request #2399
Opened 2022-02-20 12:10 UTC by MyIgel

As a follow up to #2395 / bbc00017
* Replace xhtml content type with html -> pages are interpreted as HTML5 which is the current standard and much more flexible
* Remove old xhtml workaround which is not needed anymore
* Updated `prepare_content` docs accordingly

2022-02-21 10:56 UTC, skorpy2009 approved these changes

2022-02-22 17:24 UTC, NeoRaider requested changes

2022-02-22 17:24 UTC, NeoRaider commented on docs/releases/v2016.1.rst
> +    " <br>"
Please don't change old release notes.

2022-02-22 17:48 UTC, MyIgel commented on docs/releases/v2016.1.rst
> +    " <br>"
Ärm jeah, thats a great idea & fixed :D

2022-02-22 17:51 UTC, NeoRaider approved these changes

2022-02-22 20:46 UTC, merged

2022-03-10 15:38 UTC, rubo77 commented
Nice.

Why was the XHTML tag there in the first place?

2022-03-10 17:19 UTC, MyIgel commented
I would guess legacy reasons? Meaning: It was required for some browsers to work back then and is now totally obsolete

2022-03-10 17:48 UTC, NeoRaider commented
Yeah, the code originated from LuCI, which was written before HTML5 existed. Back then XHTML was considered the future of HTML I guess (and personally I still prefer XML syntax even with HTML5 for many usecases - but for gluon-web it causes more problems than it solves).