ipq40xx-mikrotik: add mikrotik-hap-ac2
freifunk-gluon/gluon pull request #2464
Opened 2022-04-11 01:52 UTC by mkg20001

- [ ] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [ ] Other: <specify>
- [ ] Must support upgrade mechanism
  - [ ] Must have working sysupgrade
    - [ ] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [ ] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [ ] Reset/WPS/... button must return device into config mode
- [ ] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [ ] should support all network ports on the device
  - [ ] must have correct port assignment (WAN/LAN)
    - On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
      The PoE input should be the WAN port in this case.
- Wireless network (if applicable)
  - [ ] Association with AP must be possible on all radios
  - [ ] Association with 802.11s mesh must work on all radios 
  - [ ] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [ ] Lit while the device is on
    - [ ] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [ ] Should map to their respective radio
    - [ ] Should show activity
  - Switch port LEDs
    - [ ] Should map to their respective port (or switch, if only one led present) 
    - [ ] Should show link state and activity
- Outdoor devices only:
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`

2022-05-17 08:32 UTC, mkg20001 commented
Device is stuck in hungary. I'll finish up the todo list once the device comes into my hands again. :P

2022-08-09 18:53 UTC, mkg20001 commented
Wifi was not working with switched ath10k firmware, is now working with whatever vanilla ships.

2022-08-31 11:42 UTC, mkg20001 commented
Will do checklist once it's back from hungary (again).

// cc @5gbr can you remind me then? (or just do it yourself, there's a 802.11s mesh in r3 now)

2022-09-14 10:38 UTC, mkg20001 commented
primary mac is the one from wan port (both are on the label). should this be the mac of wlan or is this ok?

2022-10-24 09:06 UTC, AiyionPrime requested changes
`mikrotik-hap-ac2` has already been migrated to DSA, so it will have OpenWrt support for a while.

@blocktrron I think his mac-issue is matching our default correctly.
Keep the mac on update, but use the 'correct' label mac on settings reset.

I'd say we can merge this after he fixes the indentation. Any objections?

2022-10-24 09:06 UTC, AiyionPrime commented on targets/ipq40xx-mikrotik
> +  packages = ATH10K_PACKAGES_IPQ40XX,
indentation does not match `mikrotik-sxtsq-5-ac-rbsxtsqg-5acd` above
```suggestion
	packages = ATH10K_PACKAGES_IPQ40XX,
```

2022-12-06 06:45 UTC, AiyionPrime commented
@mkg20001 merged in #2712, thanks!

2022-12-06 06:45 UTC, closed without merging