docs: add v2021.1.2 release notes
freifunk-gluon/gluon pull request #2488
Opened 2022-04-21 21:55 UTC by NeoRaider

2022-04-21 22:58 UTC, rotanid requested changes

2022-04-21 22:58 UTC, rotanid commented on docs/releases/v2021.1.2.rst
> +* respondd-module-airtime: Fix respondd crash on devices with disable WLAN interfaces
disabled

2022-04-22 23:48 UTC, rotanid approved these changes

2022-04-27 20:42 UTC, herbetom approved these changes

2022-04-27 20:42 UTC, herbetom commented on docs/releases/v2021.1.2.rst
> +* ipq40xx: Fix bad WLAN performance on Plasmacloud PA1200 and PA2200 devices
```suggestion
* ipq40xx: Fix bad WLAN performance on Plasma Cloud PA1200 and PA2200 devices
```

2022-05-02 19:30 UTC, NeoRaider commented
- Added "unreleased" to the page title
- Mentioned upcoming critical security fix
so we can merge this PR now and finalize the release notes in a private repository with the fix.

2022-05-02 21:37 UTC, merged