Create interfaces or each "port" in /etc/config/gluon
freifunk-gluon/gluon pull request #2526
Opened 2022-05-19 20:53 UTC by lemoer

This PR enables (migration-safe) role assignment for individual "lan"
and "wan" interfaces. This is helpful especially on devices with multiple
"lan" or "wan" interfaces (as they appear for devices with DSA support).

For interfaces in /lib/gluon/lan_ifname, we now create individual
entries in /etc/config/gluon using a new introduced "/lan[0]", "/lan[1]", ...
syntax. Before this PR,  all interfaces were referenced as a single
interface "/lan" in /etc/config/gluon.

The same is done for wan_ifname and single_ifname.

Migration strategy:

If new interfaces show up during gluon-reconfigure, the assigned roles
of prior existing interfaces in the same category will be applied to the
new interface.

(This PR is based on discussions in #2490)

2022-05-20 11:39 UTC, AiyionPrime requested changes

2022-05-20 11:39 UTC, AiyionPrime commented on package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
> +	local i
```suggestion
```

That makes `i` an unused and one line later shadowed variable, doesn't it?

2022-05-29 09:46 UTC, lemoer commented
@NeoRaider What do you think?

2022-06-08 00:15 UTC, rotanid commented
PR and commit contain "or" which should be "for"

2022-06-09 07:30 UTC, lemoer commented
Thanks, fixed.

2022-06-13 15:19 UTC, NeoRaider commented on package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
> +	if type(ifnames) == 'table' then
This can't work, sysconfig always contains a string.

2022-10-30 19:15 UTC, lemoer commented on package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
> +				name = '/' .. iface .. '[' .. tostring(i) .. ']',
Ok. I will close this PR.

2022-10-30 19:16 UTC, lemoer commented
As discussed above, this PR is now closed.

2022-10-30 19:16 UTC, closed without merging