gluon-core / web: add cellular WWAN support
freifunk-gluon/gluon pull request #2631
Opened 2022-09-07 23:51 UTC by blocktrron

Add support for cellular WWAN to Gluon. This allows users to utilize integrated WWAN cards of FWA or travel routers (e.g. Teltonika / GL.iNet).

This works by creating an abstraction layer into Gluon which takes common options (SIM PIN / APN) and translates it to modem-specific settings based on the specific device using. Doing so limits the use-case onto specific models (no LTE sticks possible) but provides a common interface.

The WWAN is assigned the firewall WAN zone and wires WAN can still be used, however without prioritization, so traffic path is not configured to prefer one uplink source or the other.

![Screenshot from 2022-09-07 00-19-07](https://user-images.githubusercontent.com/16539439/189002361-ea9c3c85-5f42-4d3d-a3c9-76d7e5e0a05f.png)

2022-10-17 20:15 UTC, AiyionPrime requested changes
I find the code is easy to read and am looking forward to be able to test this in the next days.
For now the first testdevice is still with my roommate,
the second is not yet allowing me to run OpenWrt.

Looks good though, I'd like to have this in gluon.

2022-11-15 13:57 UTC, blocktrron commented
@AiyionPrime Can you have a second look here?

2022-12-04 22:32 UTC, AiyionPrime commented
The patch for my router is still open, but passed iteration four.
I rebased the OpenWrt part on 22.03, added it as patches in my local tree and added the regular gluon definitions as well as your new is_cellular` references.
After adding gluon-web-cellular` to the site.mk I was able to setup the cellular connection in configmode.

@blocktrron Not sure for how long, as the connected data volume is fairly limited; but the device works flawlessly with your code.
http://aiyion-ws-wn572hp3-4g.n.ffh.zone/cgi-bin/status or if our dns does not work:
http://[2001:678:978:221:823f:5dff:fe3b:7905]/cgi-bin/status

The device is conected via mesh-vpn, without regular wan-uplink.


I think the configmode UI should aim for sane defaults,
maybe apn: `auto`?
and if possible ipv4 or mixed could be pre-selected. Not sure what would work there best.

Last remark for tonight is, the necessity to add `gluon-web-cellular` to the site.mk manually.

The other extensions are usually just feature-decisions for the community to make, (likedo wen want node-roles), but this extension of gluon-web is device specific;
there should be a better way to ensure its on for cellular devices per default, other than adding it to communities site.mk. But that's just my two pence.


I like the code, I like the (basic) functionality, I have not tested username, password or sim-pin.

2022-12-08 09:10 UTC, AiyionPrime commented
Just stumbled across an OpenWrt patch from september.
It allows for devices to have certain metric.

Not meant to be reflected in this PR, but a follow-up.
Might be nice to have such a metric option in the UI, to allow fallback to WWAN.

https://patchwork.ozlabs.org/project/openwrt/patch/20220903123129.5713-1-zajec5@gmail.com/

2022-12-09 12:54 UTC, blocktrron commented
@AiyionPrime As mentioned yesterday, this is only metadata and does not implicit a route preference.

2022-12-13 21:13 UTC, AiyionPrime commented
@blocktrron General ack for this PR from todays gluon meetup.

2022-12-15 22:53 UTC, lemoer requested changes
Looks good to me. Good work!

Only one thing: You are trying to add an empty file `package/gluon-web-cellular/gluon-web-mesh-vpn-fastd.pot`. This doesn't seem to make sense to me.

2022-12-16 15:33 UTC, heini66 commented
thxs 4 the nice work.
for some provider, the auth feature is required to get a connection.
could you be so kind and add an dropdown menu for the auth with:
none, pap, chap or both
txs!!!

2023-01-04 19:20 UTC, lemoer approved these changes

2023-01-04 19:30 UTC, AiyionPrime approved these changes
Looks good, @lemoer and I looked over it.
Docs are below average though and Heinis suggestion might be a nice follow up.

2023-01-04 19:31 UTC, merged