docs: add Gluon v2022.1.1 Release Notes
freifunk-gluon/gluon pull request #2670
Opened 2022-10-14 15:12 UTC by blocktrron

This adds Release Notes for the Gluon v2022.1.1 release.

This is a quick take, I'd say it is kind-of-urgent given the recent publication of flaws in the wireless stack.

Not sure if we should explain the situation for older releases in this specific release notes, given 19.07 based Gluon is not affected.

2022-10-15 20:10 UTC, rotanid commented
looks good.
maybe changes committed after PR creation are missing

2022-10-16 16:24 UTC, skorpy2009 approved these changes

2022-10-17 11:44 UTC, AiyionPrime requested changes
I hope I did not miss too much; I compared this to previous releasenotes and to the commits on the branch.

2022-10-17 11:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +Gluon 2022.1
```suggestion
Gluon 2022.1.1
```

2022-10-17 11:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +   -  NanoPi R2S
in v2022.1.1 support for `NanoPi R4S (4GB LPDDR4)` has been added in #2633 hence #2649

2022-10-17 11:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +
```suggestion
ipq40xx-generic
~~~~~~~~~~~~~~~

- GL.iNet

  - gl-ap1300
```

has been added in #2649

2022-10-17 11:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> + * Fixes the update path for GL-AR300M devices.
for `ubiquiti-loco-m-xw` as well
https://github.com/freifunk-gluon/gluon/commit/9667075b540b80d94e35b604728bdb3badfbf768

2022-10-17 11:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +   -  MF281
```suggestion
```

The device is still marked as broken. As such it is not yet supported, right?

https://github.com/freifunk-gluon/gluon/pull/2637/files#diff-cdff5087c568afbf34e2d9c56309ad79c06ddb976f97a04b0c206e34d6065990R37

2022-10-17 12:38 UTC, AiyionPrime commented
@blocktrron I'll add the doc entries once #2675 is backported and #2674 is done as well.

2022-10-17 15:02 UTC, T-X requested changes

2022-10-17 16:35 UTC, herbetom commented on docs/releases/v2022.1.1.rst
> +
`GL-AP1300` please

2022-10-17 16:37 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +
done

2022-10-17 21:17 UTC, mweinelt commented on docs/releases/v2022.1.1.rst
> +
Why did you put one CVE in brackets?

> People using the gluon-mesh-wireless-sae or gluon-wireless-encryption-wpa3 packages (even though they depend on WolfSSL) should not be affected as TLS should only be used in encrypted WLAN scenarios where WPA-Enterprise is used.

Instead maybe:

> Firmware using either `gluon-mesh-wireless-sae` or `gluon-wireless-encryption-wpa3` are unaffected by this issues, since only WPA-Enterprise relies on the affected TLS functionality.

2022-10-17 21:19 UTC, rotanid commented on docs/releases/v2022.1.1.rst
> +   -  NanoPi R2S
where's the difference between those two suggestions? maybe i just don't see it...

2022-10-17 21:21 UTC, herbetom commented on docs/releases/v2022.1.1.rst
> +   -  NanoPi R2S
It's the same. I've edited mine because at that point i was thinking that that way nobody would apply the wrong one ...

Maybe not the best way to do that. Sorry

2022-10-17 22:06 UTC, T-X requested changes

2022-10-17 22:06 UTC, T-X commented on docs/releases/v2022.1.1.rst
> +This release mitigates multiple flaws in the Linux wireless stack causing RCE as well as DoS vulnerabilities.
```suggestion
This release mitigates multiple flaws in the Linux wireless stack causing RCE as well as DoS vulnerabilities. This affects Gluon v2022.1, older Gluon versions are unaffected.
```

2022-10-17 22:06 UTC, T-X commented on docs/releases/v2022.1.1.rst
> + * Multiple mitigations for (`critical vulnerabilities <https://seclists.org/oss-sec/2022/q4/20>`_) in the Linux kernel
```suggestion
 * Multiple mitigations for (`critical vulnerabilities <https://seclists.org/oss-sec/2022/q4/20>`_) in the Linux kernel WLAN stack. Only affects Gluon v2022.1, older Gluon versions are unaffected.
```

2022-10-17 22:21 UTC, T-X commented on docs/releases/v2022.1.1.rst
> +
I had put CVE-2022-38153 in brackets as it is listed on the OpenWrt page. However it seems not to affect us / our OpenWrt versions as the CVE says "however, only version 5.3.0 is exploitable". In Gluon v2021.1.2 we used WolfSSL 5.2.0-stable and in Gluon v2022.1 we used WolfSSL 5.4.0-stable.

I removed that CVE completly now to avoid confusion.

The other comment sounds good to me, too, I added your suggestion, thanks.

2022-10-17 22:34 UTC, T-X commented on docs/releases/v2022.1.1.rst
> +This release mitigates multiple flaws in the Linux wireless stack causing RCE as well as DoS vulnerabilities.
@blocktrron 
> Not sure if we should explain the situation for older releases in this specific release notes, given 19.07 based Gluon is not affected.

I would say yes, so that people know how they would need to handle their 4MB devices for instance. We can avoid the confusion of people asking when a backport to v2021.1.x would be available by be being proactive about this.

2022-10-18 01:37 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +   -  NanoPi R2S
resolved in 73bbf94427af4bf55e228a1d4afb5cbac3600a35

2022-10-18 01:44 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> + * Fixes the update path for GL-AR300M devices.
resolved in b33217ebbd31b2413b54ff0d87660c91c0b0a577

2022-10-18 01:46 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +This release mitigates multiple flaws in the Linux wireless stack causing RCE as well as DoS vulnerabilities.
Given the amount of questions regarding this in the last two days I agree.

2022-10-18 01:50 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> + * Multiple mitigations for (`critical vulnerabilities <https://seclists.org/oss-sec/2022/q4/20>`_) in the Linux kernel
This feels like the better place to leave the warning from above. Will fix my previous commit.

2022-10-18 01:56 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> + * Multiple mitigations for (`critical vulnerabilities <https://seclists.org/oss-sec/2022/q4/20>`_) in the Linux kernel
resolved in 80d219b74d35de93113f1c00d2977529239cdd03

2022-10-18 02:01 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +
The combined suggestion looks well, the CVEs check out; will put this in the PR.

2022-10-18 02:03 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +
resoolved in 9ec427df82d31e319deec4a7600937c5a3d3e748

2022-10-18 02:11 UTC, AiyionPrime requested changes
Just compiled the docs; looks fine except for the inline list of CVE.

2022-10-18 02:11 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +   * CVE-2022-38152
```suggestion

   * CVE-2022-38152
```

2022-10-18 02:11 UTC, AiyionPrime commented on docs/releases/v2022.1.1.rst
> +   * CVE-2022-41674
```suggestion

   * CVE-2022-41674
```

2022-10-18 02:16 UTC, AiyionPrime approved these changes
Fine by me.

2022-10-18 08:38 UTC, mweinelt approved these changes

2022-10-18 08:39 UTC, merged