targets/ramips-mt76x8: add device TP-Link RE200 V3
freifunk-gluon/gluon pull request #2700
Opened 2022-11-10 08:47 UTC by misanthropos

Signed-off-by: Richard Fröhning <misanthropos@gmx.de>

2022-11-10 09:17 UTC, AiyionPrime commented
Closing in favor of the existing #2086 with the very same branch ([misanthropos:re200v3](https://github.com/misanthropos/gluon/tree/re200v3)).

2022-11-10 09:24 UTC, AiyionPrime commented
My bad. As @blocktrron already stated in the old PR it was not opened against master, but next.
Anyone missing the history can read up on #2086.

2022-11-10 09:33 UTC, AiyionPrime requested changes
@misanthropos from which build are your test results?
Does wifi really work for this revision on both radios without errors?

If nothing else, please add the device to `docs/user/supported_devices.rst`.

2022-11-10 10:32 UTC, misanthropos commented
> @misanthropos from which build are your test results? Does wifi really work for this revision on both radios without errors?

Tested with: gluon v2022.1.1 with FFM feature-gluon-2022.1

Both radios are connectable and show according SSIDs including mesh IDs.
Tested 2.4G meshing via phone communicating on 5G with router which has been placed near a FFFM router without attached network cable.
Meshing on 5G must still be tested due to lack of a second test device with 5G capabilities.

2022-11-10 10:53 UTC, AiyionPrime commented
Please update the checklist accordingly.

2022-11-14 09:48 UTC, AiyionPrime requested changes
Looking at the 5GHz problems with rev4 I'd recommend testing 5GHz mesh and client network work in parallel. Leaving those two tests out feels like pushing our luck.

Find a proper mesh partner and leave them running for a day or so without crashing interfaces while a client is connected to the device and I'm fine with merging this.

2022-11-14 09:48 UTC, AiyionPrime commented on docs/user/supported_devices.rst
> +  - RE200 (v3)
```suggestion
  - RE200 (v2, v3)
```

2022-11-14 09:48 UTC, AiyionPrime commented on docs/user/supported_devices.rst
> +  - RE200 (v3)
The Archer C50 above is a bad example, sorry for the nitpick.

2022-11-14 10:43 UTC, AiyionPrime commented on docs/user/supported_devices.rst
> +  - RE200 (v3)
I proposed to take care of the C50 in #2704, no need to add it to your PR :)

2022-11-15 13:01 UTC, AiyionPrime commented
Files do look fine. Let us know, when the checklist is completed.

> Looking at the 5GHz problems with rev4 I'd recommend testing 5GHz mesh and client network work in parallel. Leaving those two tests out feels like pushing our luck.
> 
> Find a proper mesh partner and leave them running for a day or so without crashing interfaces while a client is connected to the device and I'm fine with merging this.

2022-11-15 13:14 UTC, AiyionPrime approved these changes

2022-12-02 08:30 UTC, misanthropos commented
> > Find a proper mesh partner and leave them running for a day or so without crashing interfaces while a client is connected to the device and I'm fine with merging this.

Done and dusted. No problems so far.

2022-12-02 15:15 UTC, merged