ramips-mt7621: add TP-Link Archer C6 v3
freifunk-gluon/gluon pull request #2716
Opened 2022-12-07 22:19 UTC by Kistelini

- [ ] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [ ] Other: <specify>
- [ ] Must support upgrade mechanism
  - [ ] Must have working sysupgrade
    - [ ] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [X] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [ ] Reset/WPS/... button must return device into config mode
- [X] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [X] should support all network ports on the device
  - [X] must have correct port assignment (WAN/LAN)
    - On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
      The PoE input should be the WAN port in this case.
- Wireless network (if applicable)
  - [X] Association with AP must be possible on all radios
  - [X] Association with 802.11s mesh must work on all radios 
  - [X] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [X] Lit while the device is on
    - [ ] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [X] Should map to their respective radio
    - [X] Should show activity
  - Switch port LEDs
    - [ ] Should map to their respective port (or switch, if only one led present) 
    - [ ] Should show link state and activity
- Outdoor devices only:
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
- Docs:
  - [X] Added Device to `docs/user/supported_devices.rst`

2022-12-07 22:27 UTC, Kistelini commented
Testing isn't finished. There's a problem with the LAN LED: `gluon-reconfigure` generates this piece for `/etc/config/system`
```
config led 'led_lan'
	option name 'LAN'
	option sysfs 'green:lan'
	option trigger 'netdev'
	option mode 'link tx rx'
	option dev 'br-lan'
```
because of [these defaults](https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/mt7621/base-files/etc/board.d/01_leds#L150), but Gluon doesn't have `br-lan`  so the LED doesn't work. How do I fix this?

2022-12-07 23:54 UTC, Kistelini commented
Those `mt7530-*` triggers don't do anything. Everything else works!

2022-12-11 23:51 UTC, blocktrron commented
I think we have to take a look at software-controlled LEDs spanning multiple LAN ports in conjunction with DSA, as this is currently not handled nicely upstream. I assume some other devices have lost sane handling with migrating to DSA also.

2023-01-10 19:50 UTC, AiyionPrime requested changes
@Kistelini Sorry this took so long, took a moment to understand how swconfig did it and why this is not trivial to fix upstream.
I'd like to add the expiration note for when the broken status is expected to be fixed, but other than that the PR looks fine.

2023-01-10 19:50 UTC, AiyionPrime commented on targets/ramips-mt7621
> +	broken = true, -- LAN LED not working
```suggestion
	broken = true, -- LAN LED not working - review after resolving #2756
```

2023-01-10 20:18 UTC, merged

2023-01-29 23:50 UTC, Djfe commented
Should we add the Archer A6 v3 as well? They share the exact same dtsi/dts, the same led config etc. They just have a different name, which might influence the tp-link safeloader. (so it probably has to be a different entry instead of an alias, right?)

2023-01-30 07:42 UTC, AiyionPrime commented
As soon as someone wants to use the device, we've got someone to test it.
We usually do not merge untested devices anymore. Even if we think the difference is minor and it should just work.
Whoever wants to use and test it, will have a smooth run integrating it :)

2023-04-11 19:56 UTC, Djfe commented
@AiyionPrime backport needed

2023-04-17 22:02 UTC, AiyionPrime commented
> @AiyionPrime backport needed

Won't happen, it's broken.

We'll publish the list of upcoming backports in the tracking issue tomorrow morning again. (Hoping GitHub does not eat it twice -.-')