docs: remove remaining CSS workaround
freifunk-gluon/gluon pull request #2737
Opened 2022-12-27 17:11 UTC by NeoRaider

Remove a workaround for a CSS issue in older Firefox versions, which was recently fixed (at some point between Firefox 102 and 108). Firefox 108+ now display the bullet points at the right vertical position even without the hack in [1].

[1] https://gluon.readthedocs.io/en/latest/releases/v2018.1.html#site-conf

Opening as a draft for now, as the current Extended Support Release is Firefox 102. I propose to merge this as soon as all Firefox versions without the fix are EOL.

2023-01-10 19:32 UTC, AiyionPrime commented
So if the fix does not make it into an upcoming point version of 102.x ESR,
the latest this will be merged is the 26th September this year, when 102 goes EOL and 115 will be the only supported ESR? [1]

The next ESR release dates are 17th of this month (102.7), and 14th February (102.8);
the later being the one likely to include this fix.


[1] https://wiki.mozilla.org/Release_Management/Calendar

2023-01-10 19:40 UTC, AiyionPrime commented
Line 104 to 107 should be gone as well, as this is effectively the last artifact of #2078, right?

https://github.com/freifunk-gluon/gluon/commit/96f1547d0f3dabe8b0dc0ae4399f518e5dd575b2#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R104-R107

2023-01-10 19:41 UTC, AiyionPrime requested changes
Line 104 to 107 in `docs/conf.py` should be gone as well, as this is effectively the last artifact of #2078, right?

https://github.com/freifunk-gluon/gluon/commit/96f1547d0f3dabe8b0dc0ae4399f518e5dd575b2#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R104-R107

2023-01-13 18:58 UTC, NeoRaider commented
> Line 104 to 107 in `docs/conf.py` should be gone as well, as this is effectively the last artifact of #2078, right?
> 
> [96f1547#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R104-R107](https://github.com/freifunk-gluon/gluon/commit/96f1547d0f3dabe8b0dc0ae4399f518e5dd575b2#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R104-R107)

Fixed

2023-01-13 20:06 UTC, AiyionPrime approved these changes

2023-09-27 21:30 UTC, neocturne commented
Current Firefox ESR is 115.x, so we can finally merge this.

2023-09-28 08:45 UTC, merged