gluon-web-cellular: add German translation
freifunk-gluon/gluon pull request #2767
Opened 2023-01-23 13:14 UTC by herbetom

![image](https://user-images.githubusercontent.com/15121114/214048409-db3cceec-7995-4323-9e3c-418285390af4.png)

2023-01-23 22:10 UTC, blocktrron approved these changes
lgtm

2023-01-24 13:42 UTC, AiyionPrime requested changes
Other than those two it looks fine.

2023-01-24 13:42 UTC, AiyionPrime commented on package/gluon-web-cellular/i18n/de.po
> +"dich dafür entscheidest wird die VPN Verbindung über das integrierte "
```suggestion
"dich dafür entscheidest, wird die VPN-Verbindung über das integrierte "
```

2023-01-24 13:42 UTC, AiyionPrime commented on package/gluon-web-cellular/i18n/de.po
> +"Mobilfunk Modem hergestellt."
```suggestion
"Mobilfunkmodem hergestellt."
```
or
```suggestion
"Mobilfunk-Modem hergestellt."
```

would be fine, but the space is not.

2023-01-24 15:13 UTC, AiyionPrime approved these changes

2023-01-24 18:20 UTC, merged