extended info when no domain is given
freifunk-gluon/gluon pull request #2790
Opened 2023-02-19 13:59 UTC by cptechnik

... the easy way ... 
the better way is ... a parameter to get domain status... like gluon-switch-domain status  --> uci get gluon.core.domain ...but... until then... this is helpful...

2023-02-24 13:06 UTC, AiyionPrime requested changes
Hey @cptechnik, first of all thanks for your contribution!
As you already identified your solutions room for improvement, I'd recommend implementing that instead.

Your referenced approach of adding a parameter to `gluon-switch-domain` to show the current domain looks unclean in my eyes, as that would not switch the domain anymore.

A cleaner approach would be to extend `gluon-info`, a rather new tool that already emits node specific information like *Firmware release*, *Site* and *Gluon version*.
Adding the current domain would finish of which part of the site is currently active.

The file of `gluon-info`is this: https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-core/luasrc/usr/bin/gluon-info

I don't expect the implementation to be too troublesome, if you've got questions feel free to ask.

2023-03-25 00:31 UTC, AiyionPrime commented
@cptechnik Are you still interested in this (and do you have questions)?

2023-03-26 20:53 UTC, cptechnik commented
> @cptechnik Are you still interested in this (and do you have questions)?
yes interested.

yes, maybe in gluon-info is a very good place.

but, not unusefull to integreate a error catching function in switch-domain... if the input is not right or available, the output of switch-domain could be the available parameters like a bash command without parameters

sorry my english is not so good to explain everything turning around in my brain...

2023-03-26 20:58 UTC, AiyionPrime commented
@cptechnik Wir versuchen hier auf englisch zu schreiben, um möglichst vielen Lueten die Möglichkeit zu geben, aus vergangenen PullRequests und Issues zu lernen.
Wenn dich das einschränkt, kannst du aber gerne deutsch schreiben.
Dich wollen wir schließlich auch nicht ausgrenzen.

2023-03-26 21:17 UTC, AiyionPrime commented
Es gibt aktuell zwei Dinge die ich in diesem Kontext sinnvoll finde.
Einmal die Info, die dein PR aktuell vorschlägt: Das Anzeigen der aktuellen Domain.
Die gehört in meinen Augen in `gluon-info`, wie oben beschrieben.

Das zweite ist, dass man `gluon-switch-domain` nicht aufrufen würde, um auf die aktuelle Domain zu wechseln.
Der Hinweis den du gerade in der Fehlermeldung gibst, wie auch der Vorschlag das in gluon-info zu tun, helfen mMn. in dem Szenario einfach nicht.

Gegebenen Falls wäre es in der Situation sinnvoller, eine Liste der möglichen Domains auszugeben. Vielleicht auch nicht, denn die Liste ungefragt als Fehlermeldung rauszuhauen könnte lang werden.

2023-03-26 21:19 UTC, cptechnik commented
Ganz woanders "durfte" ich nicht deutsch weiterschreiben... deshalb bin ich vorsichtig ...

Ist denn jetzt verstanden was ich meinte...

Klar, ist gluon-info ein Informations-Täfelchen, auf dem die Informationen abgefragt werden können, ...
...aber der Befehl das umzusetzen ist gluon-switch-domain, und könnte durch meinen kleinen input einfach helfen,... wie an der Linux Konsole eben auch statt nur -error- auszugeben wird ein Hinweis auf korrekte Bedienung ausgegeben...
...das meinte ich...
Manch eine Domain heisst eben nicht nur "Berlin", vielleicht heisst sie "berlin-innenstadt" oder "b_Berlin-innen"... und ein Abfrage-Menü wäre definintiv zu viel...

Alternative wäre auch...
im Fehlerfall direkt gluon.core oder gluon-info aufrufen/abrufen, um einen Hinweis auf die korrekte Domain zu geben...

Das alles macht aber viel mehr Code, und daher mein kurzer Hinweis:
'Usage: gluon-switch-domain [--no-reboot] <domain>\nUse: "uci show gluon.core" to view your actual domain\n'
anstatt
'Usage: gluon-switch-domain [--no-reboot] <domain>\n'
Mit wenig Code viel erreichen... 
...wie hiess jetzt nochmal die Domain, und wo steht  die...

2023-03-26 21:24 UTC, AiyionPrime commented
Ich will nicht unhöflich wirken, aber den PR so anzunehmen, wie er jetzt ist, steht ausser Frage. Er wird aktuell nicht den Maßstäben gerecht, die wir an den Code in der Repo legen.

Wenn wir Probleme nicht direkt richtig lösen, müssen wir die Baustelle irgendwann nochmal anfassen, das verschwendet zu viel Zeit, die wir als Kernentwickler sowieso nicht unbegrenzt haben.

Ich hoffe das hilft dir erstmal weiter, melde dich gerne, wenn du Fragen hast.

2023-03-26 22:58 UTC, cptechnik commented
> PR
nicht verstanden.

2023-03-26 23:02 UTC, cptechnik commented
> Wenn wir Probleme nicht direkt richtig lösen, müssen wir die Baustelle irgendwann nochmal anfassen, das verschwendet zu viel Zeit, die wir als Kernentwickler sowieso nicht unbegrenzt haben.

Ich verstehe nicht, warum ein erweiterte Rückmeldung... 
statt 
'Usage: gluon-switch-domain [--no-reboot] \n'
diese
 'Usage: gluon-switch-domain [--no-reboot] \nUse: "uci show gluon.core" to view your actual domain\n'
erweiterte Fehlermeldung drin sein kann.
Ich kann auch nicht nachvollziehen was den Code jetzt so schaden könnte...

Ich bin hier aber auch nur Quereinsteiger, und dachte mit einer erweiterten Fehlermeldung denjenigen zu helfen, die nicht alle Befehle im Kopf haben...

War ja auch nur ein Vorschlag, den man ablehnen kann.

2023-03-27 20:35 UTC, AiyionPrime commented
> Ich verstehe nicht, warum ein erweiterte Rückmeldung... statt 'Usage: gluon-switch-domain [--no-reboot] \n' diese 'Usage: gluon-switch-domain [--no-reboot] \nUse: "uci show gluon.core" to view your actual domain\n' erweiterte Fehlermeldung drin sein kann. Ich kann auch nicht nachvollziehen was den Code jetzt so schaden könnte...

Hattest du die beiden Begründungen von mir darüber denn gelesen? :)
https://github.com/freifunk-gluon/gluon/pull/2790#issuecomment-1484226684

> Ich bin hier aber auch nur Quereinsteiger, und dachte mit einer erweiterten Fehlermeldung denjenigen zu helfen, die nicht alle Befehle im Kopf haben...

Die Fehlermeldung zu verbessern ist auf jeden Fall eine gute Idee.

> War ja auch nur ein Vorschlag, den man ablehnen kann.

Joa. Aber das Ziel ist ja nicht abzulehnen, was noch nicht ganz ausgereift ist, sondern dir zu zeigen, dass deine Idee Potential hat und dir zu erklären, wo es liegt,
sodass du mit wenig Aufwand ein gutes Ergebnis erzielen kannst und dem Projekt etwas zurückgeben kannst :)

2023-04-16 20:56 UTC, maurerle commented
Ich denke man kann hier stattdessen
`{ 'Domain', uci:get('gluon', 'core', 'domain') or 'n/a' },`
nach Zeile 28:
https://github.com/freifunk-gluon/gluon/blob/297cd5bc3f284f4911d962d481640931d8d60ab4/package/gluon-core/luasrc/usr/bin/gluon-info#L28
hinzufügen.
Das ist auch nur ein Einzeiler und würde hier vielen weiter helfen.

Wenn ich meine Domain ändern will, hilft mir die aktuelle Domain ja auch nicht so viel - da müsste man schon einen Hinweis auf `ls /lib/gluon/domains` geben, was jetzt auch nicht grade schön ist.
Man bräuchte zusätzlich also etwas wie `gluon-list-domains`, das ist dann aber etwas für einen zweiten Pull Request :blush:

2023-05-09 23:23 UTC, blocktrron commented
Closing due to lack of progress. Feel free to re-open once the requested changes are implemented.

2023-05-09 23:23 UTC, closed without merging