ramips-mt7621: add support for D-Link DAP-X1860 (A1)
freifunk-gluon/gluon pull request #2830
Opened 2023-03-27 20:12 UTC by herbetom

still needs a openwrt-22.03 backport, working on it

- [ ] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [ ] Other: <specify>
- [ ] Must support upgrade mechanism
  - [ ] Must have working sysupgrade
    - [ ] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [ ] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [ ] Reset/WPS/... button must return device into config mode
- [ ] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [ ] should support all network ports on the device
  - [ ] must have correct port assignment (WAN/LAN)
    - if there are multiple ports but no WAN port:
      - the PoE input should be WAN, all other ports LAN
      - otherwise the first port should be delcared as WAN, all other ports LAN
- Wireless network (if applicable)
  - [ ] Association with AP must be possible on all radios
  - [ ] Association with 802.11s mesh must work on all radios 
  - [ ] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [ ] Lit while the device is on
    - [ ] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [ ] Should map to their respective radio
    - [ ] Should show activity
  - Switch port LEDs
    - [ ] Should map to their respective port (or switch, if only one led present) 
    - [ ] Should show link state and activity
- Outdoor devices only:
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
- Docs:
  - [ ] Added Device to `docs/user/supported_devices.rst`

2023-03-27 20:29 UTC, AiyionPrime requested changes
Looks good, thanks for picking this up.
Might be one of the cheapest WiFi 6 devices we'll encounter for a while.

2023-03-27 20:29 UTC, AiyionPrime commented on docs/user/supported_devices.rst
> +  - D-Link DAP-X1860 (A1)
```suggestion
  - DAP-X1860 (A1)
  - DIR-860L (B1)
```

2023-03-27 20:29 UTC, AiyionPrime commented on modules
> +OPENWRT_BRANCH=openwrt-22.03_dlink-dap-x1860-a1
Looking forward for the backport, let me know when you need a tester.

2023-03-27 20:29 UTC, AiyionPrime commented on targets/ramips-mt7621
> +device('d-link-dap-x1860-a1', 'dlink_dap-x1860-a1')
Same as above, `dap` before `dir`.

2023-03-28 01:02 UTC, herbetom commented
The Device has no Radio LEDs but there are 4 (currently unused) RSSI Leds in three positions:

```
root@64xxx-a8637d2e9378:~# ls -1 /sys/class/leds/ | grep rssi
green:rssihigh
green:rssilow
green:rssimedium
orange:rssilow
```

Hoewer, apart from an arbitrary mapping, i'm lacking a good idea how they could be used as Radio LEDs for the two Radios.

2023-03-28 08:49 UTC, AiyionPrime commented
> The more lit green bars on the Signal Indicator LED, the better the wireless signal to the host network. A
> single solid orange LED indicates a weak Wi-Fi signal.

And

>  If the extender has been configured as an access point and is 
> connected via an Ethernet cable to an uplink network, the Signal Indicator LED will not be lit.

So in stock it is not used as fixed to one of the radios.

2023-03-28 12:48 UTC, s-2 commented
> The Device has no Radio LEDs but there are 4 (currently unused) RSSI Leds in three positions:

As far as I recall, the `rssileds` bargraph was working at some point in one of the test builds back then, the issue was mostly about OpenWrt having introduced dynamic interface names for associations as a client. But this affected all devices using the `rssileds` package.
For gluon based on OpenWrt 22, I would have assumed the bargraph would work right away (when meshing over `wlan1`, which is probably 5GHz), but it's been too long since I've tested this, maybe I had changed the rssileds interface in uci to match gluon (however for other devices like DAP-1330 there was no special care needed for the bargraph to work).

2023-03-30 22:46 UTC, herbetom commented
Closing this for now. There are some issues with the flash which need to be resolved before this is feasible.

2023-04-09 10:05 UTC, herbetom commented
I'll update this once #2844 has been merged.

2023-04-09 17:56 UTC, herbetom commented
I haven't yet tested the latest bump (i'm not expecting problems since only the location of the patches has changed, but i still would like to test it of course). Once i've done that i'll remove the draft state.

2023-04-11 19:35 UTC, AiyionPrime approved these changes
Looks good, I'd wait for someone that has tested this device like @s-2 or @Dark4MD who offered to test it this afternoon; If this has been tested enough, I'd be fine with merging as well.

2023-04-11 19:54 UTC, AiyionPrime commented
feel free to remove the label, if you want to merge this earlier.

2023-04-12 16:50 UTC, Djfe commented
I get like 33% packetloss in mesh mode... :/
https://pastebin.com/rwed9X90

batman reports throughput varying between 8 and 56mbit/s 
https://pastebin.com/wrMSepcP
This is with a Linksys MR8300 as an offloader. 5GHz mesh only (for testing, I also tested 2.4GHz)
I had an instable connection with an tp-link archer c6 v2 before as well. Going to test my Asus RT-AX53U now.

It takes minutes for the device to get a working connection, when I disable and enable wifi on the offloading site.
I can't reach the status page, nor do I get an ip in the wifi, then I get an ip, but neither speedtests nor website loading works.

2023-04-12 18:17 UTC, herbetom commented
Setup: Extreme Networks WS-AP3825i with uplink, the D-Link DAP-X1860 (A1) is connected via WiFi Mesh. Test is done from the D-Link over the Internet. (Also not connected to the best Gateway Setup we've got so the few missing Pings could be anything.)

I'm not seeing an relevant ammount of packet loss.

```
root@64xxx-a8637d2e9248:~# ping 2a09::
PING 2a09:: (2a09::): 56 data bytes
64 bytes from 2a09::: seq=0 ttl=61 time=32.387 ms
64 bytes from 2a09::: seq=1 ttl=61 time=34.067 ms
...
64 bytes from 2a09::: seq=2100 ttl=61 time=32.913 ms
^C
--- 2a09:: ping statistics ---
2101 packets transmitted, 2093 packets received, 0% packet loss
round-trip min/avg/max = 31.740/33.263/63.611 ms
```

Regarding Traffic: I've tested it with iperf3 from the D-Link Node. I'm seeing about 25 Mbit/s. It's nothing incredible but also nothing about which i'm incredibly worried immediately. And the test was done from the device that's beeing tested ...


@Djfe I'm happy you've found the Edit Button after your second message ;)

2023-04-13 17:10 UTC, Djfe commented
Sorry for the noise yesterday. Today the issue is fixed. It actually was partially caused by our backend.
They worked on it yesterday, and now everything works as expected, which I'm very glad about :)
Thanks for taking a look and confirming, that it wasn't caused by the device!

I tested everything and can confirm the device integration test now that meshing works for me.
Using Firefox for flashing the router only reports a 1kB file instead of several MBs. (if anyone wants to debug this, they need to take a look what makes the file transmission fail)

2023-04-13 21:12 UTC, merged

2023-04-21 11:27 UTC, s-2 commented
Looking at the serial console of a recent master build, a couple of these occur once the device has booted:

```
[   72.397731] ------------[ cut here ]------------
[   72.403036] WARNING: CPU: 0 PID: 3647 at backports-5.15.92-1/net/mac80211/mesh_hwmp.c:353 airtime_link_metric_get+0x120/0x684 [mac80211]
[   72.415410] Modules linked in: iptable_nat batman_adv xt_state xt_nat xt_conntrack xt_REDIRECT xt_MASQUERADE xt_CT nf_nat nf_conntrack mt7915e mt76_connac_lib mt76 mac80211 ipt_REJECT ebtable_nat ebtable_filter ebtable_broute cfg80211 xt_time xt_tcpudp xt_quota xt_pkttype xt_owner xt_multiport xt_mark xt_mac xt_limit xt_comment xt_addrtype xt_TCPMSS xt_LOG ts_kmp ts_fsm ts_bm nf_reject_ipv4 nf_log_ipv6 nf_log_ipv4 nf_log_common nf_defrag_ipv6 nf_defrag_ipv4 iptable_mangle iptable_filter ip_tables hwmon ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 compat sch_teql sch_sfq sch_multiq sch_gred sch_fq sch_dsmark sch_codel em_text em_nbyte em_meta em_cmp act_simple act_pedit act_csum libcrc32c sch_htb sch_hfsc em_u32 cls_u32 cls_route cls_matchall cls_fw cls_flow act_skbedit act_mirred act_gact ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 dummy ip_tunnel
[   72.416042]  veth tun vxlan udp_tunnel ip6_udp_tunnel sha256_generic libsha256 seqiv jitterentropy_rng drbg hmac cmac leds_gpio cls_basic sch_tbf sch_ingress gpio_button_hotplug crc32c_generic
[   72.521115] CPU: 0 PID: 3647 Comm: respondd Tainted: G        W         5.10.176 #0
[   72.528768] Stack : 809a0000 00000580 807c82fc 8007c8a0 80840000 80730c00 00000000 00000000
[   72.537141]         826bda14 80980000 807010ec 817c03c0 807cadc7 00000001 826bd9b8 0966e35d
[   72.545501]         00000000 00000000 807010ec 826bd858 ffffefff 00000000 ffffffea 00000000
[   72.553845]         826bd864 00000273 807cfa90 ffffffff 80000000 00000001 00000000 80700000
[   72.562190]         00000009 82a58da0 816cf1f0 00000580 00000018 803a6420 00000000 80980000
[   72.570534]         ...
[   72.572974] Call Trace:
[   72.575432] [<80007fd0>] show_stack+0x30/0x100
[   72.579872] [<80320a3c>] dump_stack+0x9c/0xcc
[   72.584230] [<8002ff2c>] __warn+0xb0/0x11c
[   72.588308] [<8002fff4>] warn_slowpath_fmt+0x5c/0xac
[   72.593390] [<82d6c5d8>] airtime_link_metric_get+0x120/0x684 [mac80211]
[   72.600042] [<82d09018>] sta_set_sinfo+0x7e0/0x1090 [mac80211]
[   72.605901] [<82d240a0>] ieee80211_nan_func_match+0x14bc/0x2214 [mac80211]
[   72.612850] [<82c2dc90>] nl80211_put_sta_rate+0x140c/0x15e0 [cfg80211]
[   72.619412]
[   72.621778] ---[ end trace ecbb70bc1ec2a64d ]---
```
It seems like they might be caused by the `rssileds` package, which is configured to interface `wlan1` as per OpenWrt `01_leds`. Since the interface name does not exist (and is apparently not silently mapped to anything else), no bargraph is displayed.
Changing this to `mesh1` will show the LED bargraph, and lots of further warnings like the one above are printed:
```
uci set system.rssid_wlan1.dev='mesh1'
uci commit system
/etc/init.d/rssileds restart
```
However it seems to be stuck at two green LEDs, no matter how close I put it to another 5GHz device :thinking: