add device_integration github issue template
freifunk-gluon/gluon pull request #2846
Opened 2023-04-11 20:52 UTC by maurerle

this *should* add a device_integration github issue template.
I don't know if there is an easy way to test this.

2023-04-11 22:54 UTC, herbetom requested changes
testing is possible for example via 

https://github.com/maurerle/gluon/compare/feature/device_integration...herbetom:gluon:add_linksys-ea8300

Also this template shouldn't be the only one. Not everything is device support.

2023-04-11 22:54 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +`ramips-mt7621: add Xiaomi Mi Router 4A`
I would prefer a less shitty device as an example, also the syntax in the past was mostly "add support for" AFAIK. Why did you leave out the "(Gigabit Edition)"?

```suggestion
Please name your PR like "$TARGET: add support for $DEVICE_NAME".
For example, to add Xiaomi Mi Router 4A (Gigabit Edition) name the PR:
`ramips-mt7621: add support for Xiaomi Mi Router 4A (Gigabit Edition)`
```

2023-04-11 22:54 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +
```suggestion
All pull requests should target master. A backport can be made afterwards and is welcomed (as long as it is easy to realize). Next is not a valid target.

```

2023-04-11 22:54 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +-->
```suggestion
```
duplicate

2023-04-11 22:54 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +**Gluon Version:**
Mhm, what's the point? The tests should be done with the state of the Commit.


```suggestion
```

2023-04-11 22:59 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +### Device Integration Checklist
```suggestion
```

probably not necessary

2023-04-11 23:01 UTC, herbetom commented on .github/PULL_REQUEST_TEMPLATE/device_integration.md
> +  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
```suggestion
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
 - Cellular devices only:
  - [ ] Added board name to `is_cellular_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
  - [ ] Added board name with modem setup function `setup_ncm_qmi` to `package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular`
```

2023-04-12 00:54 UTC, maurerle commented
So I found out, that it works having a `.github/PULL_REQUEST_TEMPLATE.md` but not of if you are using `.github/PULL_REQUEST_TEMPLATE/my_template.md`

any suggestions?

2023-04-12 11:28 UTC, herbetom commented
Yeah, seems like that multiple Templates are only somewhat supported. It's possible to use those templates if you use a parameter in your URL to create the PR:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request

Maybe it's possible to link from `github/pull_request_template.md` to the correct template? But probably not easily and elegantly possible.

Astonishing that multiple Pull Request Templates aren't a thing.

2023-04-12 11:36 UTC, maurerle commented
When pushing a branch, the git remote respondes with:

```
remote: Create a pull request for 'feature/test' on GitHub by visiting:
remote:      https://github.com/maurerle/gluon/pull/new/feature/device_integration
```

which doesn't give such an option too.

This works:
https://github.com/maurerle/gluon/compare/feature/device_integration...herbetom:gluon:add_linksys-ea8300?quick_pull=1&template=device_integration_template.md

But currently, the feature is not very useful.
We could merge it either, and hope that it works some day with some kind of dropdown menu.. But then we can reopen this too

2023-04-12 11:36 UTC, closed without merging