docs: Add v2022.1.4 release notes
freifunk-gluon/gluon pull request #2878
Opened 2023-04-24 13:08 UTC by blocktrron

Add Release notes for the Gluon Release v2022.1.4.

The commit adding Release-Notes requires to be forward-ported to master.

2023-04-24 16:12 UTC, AiyionPrime requested changes
Mainly linting stuff.

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion


```

lines contain two spaces each

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion

```

line contains two spaces. I'm not arguing to remove the line, but the spaces. GitHubs UI is weird regarding empty lines.

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion

```

line contains two spaces

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion

```

line contains two spaces

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion


```

lines contain two spaces each

2023-04-24 16:12 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +   (`#2784 <https://github.com/freifunk-gluon/gluon/issues/2784#issuecomment-1452126501>`_)
```suggestion
* Enterasys WS-AP3705i now uses the correct image-name for use with the autoupdater
  (`#2819 <https://github.com/freifunk-gluon/gluon/issues/2819>`_)

* Reduce memory Usage for ath10k on ZyXEL WRE6606 devices
  (`#2842 <https://github.com/freifunk-gluon/gluon/issues/2842>`_)

* Replace the Workaround for failed boots on ath79 with a proper fix
  (`#2784 <https://github.com/freifunk-gluon/gluon/issues/2784#issuecomment-1452126501>`_)
```

Amount of left padding spaces should be a multiple of two, like in the "Known issues" section.

2023-05-03 08:04 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion

- Aerohive

  - HiveAP 121
  
```

2023-05-04 22:37 UTC, blocktrron commented on docs/releases/v2022.1.4.rst
> +- D-Link
cudy x6 v1

2023-05-05 21:30 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +- D-Link
cudy x6 v2 #2891

2023-05-05 21:36 UTC, AiyionPrime requested changes

2023-05-05 21:36 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
```suggestion

- Cudy

  - X6 (v1, v2)

```

2023-05-05 21:37 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +- D-Link
https://github.com/freifunk-gluon/gluon/pull/2878#discussion_r1186516291

2023-05-06 09:55 UTC, blocktrron commented
I think we can continue here. In case somebody reall REALLY wants to have #2879 here, I expect the corresponding reference for the Release-Notes as a deliverable.

2023-05-06 10:45 UTC, AiyionPrime commented
I really want that in the release and think so does your community.
There are several ath79 devices that are effectively unusable in the current state on stable and @herbetom has not indicated negative experiences with this backport, yet.

2023-05-06 10:47 UTC, AiyionPrime requested changes

2023-05-06 10:47 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
This is the deliverable you requested, you just chose not to apply it yet, I think.

2023-05-06 11:24 UTC, AiyionPrime requested changes
As requested: the 'resolved' changes from a few weeks ago in patch form:
https://aiyionpri.me/shared/blocktrron/0001-fixup-docs-Add-v2022.1.4-release-notes.patch

2023-05-08 11:41 UTC, AiyionPrime approved these changes
Looks good; I'd suggest putting [docs/releases/v2022.1.4.rst](https://github.com/freifunk-gluon/gluon/pull/2878/files#diff-11b2ede48a1e00e492a520982a7bcbcb02d2166c089ce69f16557a72bd48a5f4) onto master and run the the editorconfig checker, before that thing bugs you upon forwardporting it later.
Currently at work.

2023-05-08 11:41 UTC, AiyionPrime commented on docs/releases/v2022.1.4.rst
> +
applied in line 109

2023-05-09 21:17 UTC, merged