ath79-generic: add Meraki MR16
freifunk-gluon/gluon pull request #2917
Opened 2023-06-15 12:27 UTC by fl0tu

So far I can see its just working fine.
Is there a checklist to get devices into master?

2023-06-15 13:57 UTC, herbetom requested changes
The Checklist that needs to be filled out is here: https://github.com/freifunk-gluon/gluon/wiki/Device-Integration-checklist

Additional Information regarding device support can be found under the following URLs:
- https://github.com/freifunk-gluon/gluon/wiki/Device-Integration
- https://gluon.readthedocs.io/en/latest/dev/hardware.html

2023-06-15 14:00 UTC, herbetom commented on targets/ath79-generic
> +})
The Vendors should be alphabetically sorted (and within the Vendors sections the devices as well).

2023-08-03 17:44 UTC, blocktrron commented
@fl0tu Are you still on this?

2023-08-04 06:25 UTC, closed without merging

2023-08-04 06:25 UTC, fl0tu commented
A lot to learn. No time.