build: allow validating image-size of resulting images
freifunk-gluon/gluon pull request #3097
Opened 2023-12-11 17:17 UTC by blocktrron

This Pull-Request adds the ability to check the resulting images from a Gluon build to be checked in terms of available image-size.

Gluon already fails in case an image is discarded due to exceeding the available size. However, this ignores the requirement of additional space for the jffs2 overlay.

Include the IMAGE_SIZE defined in OpenWrt into the profile.json. Also start copying this file to the Gluon output directory.
Add a script for validating the image-size with a customizable overhead.
Include this script into the CI action of Gluon.

2023-12-11 21:42 UTC, T-X commented on .github/workflows/build-gluon.yml
> +        run: contrib/check-image-size.sh --github-actions --overhead 256 output/meta/openwrt-profiles/${{ matrix.target }}.json
Should this be check-image-size.py instead? (or am I missing something?)

2024-07-28 16:04 UTC, Djfe commented
Interesting PR that I missed, thanks for showing it to me :)

why is overhead set to 256 in particular?
it assume it represents erase-size, so it's either:
- 4KiB *5 = 20KiB (we likely want to pad that since it's not enough for the gluon config)
- 64KiB *5 = 320KiB
- 128KiB *5 = 640 KiB
- 256KiB *5 = 1280KiB

2025-03-10 21:29 UTC, rotanid commented
@blocktrron is there a new status about the related openwrt patches? this question came up in today's meetup

2025-05-04 07:52 UTC, maurerle requested changes
There are also various trailing blank spaces which should be removed.

Other than that, this looks very good!

For me, it detected the following images as too large (quite sure that is correct):

```
False Image size of profile openmesh_om2p-hs-v1 is too big (7669183 > 7340032)
Warning: Image size of profile openmesh_om2p-hs-v1 is too big (7669183 > 7340032)
False Image size of profile openmesh_om2p-hs-v2 is too big (7669185 > 7340032)
Warning: Image size of profile openmesh_om2p-hs-v2 is too big (7669185 > 7340032)
False Image size of profile openmesh_om2p-hs-v3 is too big (7669185 > 7340032)
Warning: Image size of profile openmesh_om2p-hs-v3 is too big (7669185 > 7340032)
False Image size of profile openmesh_om2p-hs-v4 is too big (7669185 > 7340032)
Warning: Image size of profile openmesh_om2p-hs-v4 is too big (7669185 > 7340032)
False Image size of profile openmesh_om2p-lc is too big (7669177 > 7340032)
Warning: Image size of profile openmesh_om2p-lc is too big (7669177 > 7340032)
False Image size of profile openmesh_om2p-v1 is too big (7669174 > 7340032)
Warning: Image size of profile openmesh_om2p-v1 is too big (7669174 > 7340032)
False Image size of profile openmesh_om2p-v2 is too big (7669176 > 7340032)
Warning: Image size of profile openmesh_om2p-v2 is too big (7669176 > 7340032)
False Image size of profile openmesh_om2p-v4 is too big (7669176 > 7340032)
Warning: Image size of profile openmesh_om2p-v4 is too big (7669176 > 7340032)
False Image size of profile plasmacloud_pa300 is too big (7414573 > 7340032)
Warning: Image size of profile plasmacloud_pa300 is too big (7414573 > 7340032)
False Image size of profile plasmacloud_pa300e is too big (7414575 > 7340032)
Warning: Image size of profile plasmacloud_pa300e is too big (7414575 > 7340032)
```
everything else seems good

2025-05-04 07:52 UTC, maurerle commented on contrib/check-image-size.py
> +                print_warning(args.github_actions, msg)
`print_warning` is not defined

2025-05-04 07:52 UTC, maurerle commented on contrib/check-image-size.py
> +        if "image_size" in profile_data.get("file_size_limits", {}):
```suggestion
        if "image" in profile_data.get("file_size_limits", {}):
```
Otherwise this never matches

2025-05-29 07:59 UTC, maurerle commented
@blocktrron could you include the fixes I proposed please?

2025-05-29 14:20 UTC, Djfe commented on contrib/check-image-size.py
> +                print_warning(args.github_actions, msg)
it's probably an artifact from the previous solution and was replaced by line 130 and 131
So it's enough to remove line 129.

2025-06-21 16:27 UTC, merged