purge gluon-mesh-babel
freifunk-gluon/gluon pull request #3105
Opened 2023-12-13 18:20 UTC by skorpy2009

2023-12-13 18:25 UTC, blocktrron commented
@mkg20001 Can you have a look at this?

2023-12-14 00:10 UTC, mkg20001 commented on package/gluon-l3roamd/Makefile
> +  TITLE:=Configure l3roamd for l3-mesh
"for l3-mesh" is kindof superfluos since the name already implies it's layer3.

2023-12-14 00:10 UTC, mkg20001 commented on docs/user/site.rst
>    **Note:** It may be interesting to include the package *gluon-iptables-clamp-mss-to-pmtu*
i have not tested if this does anything useful on olsr

2023-12-15 14:37 UTC, herbetom requested changes
A babel refence can still be found in `.github/labeler.yml`. But that's just something i've seen randomly. Haven't grepped if there are others.

2024-01-07 22:31 UTC, merged