docs: add v2023.2.1 release notes
freifunk-gluon/gluon pull request #3168
Opened 2024-01-20 01:35 UTC by blocktrron

2024-01-20 16:16 UTC, skorpy2009 requested changes

2024-01-20 16:16 UTC, skorpy2009 commented on docs/releases/v2023.2.1.rst
> +* Nodes using a fastd VPN connection now report the negotiated method on the Status-Page
```suggestion
* Nodes using a fastd VPN connection now report the negotiated method on the status page
```

2024-01-20 16:16 UTC, skorpy2009 commented on docs/releases/v2023.2.1.rst
> +* Spurious reboot issues on some TP-Link WDR3600 and WDR4300 devices have been fixed
```suggestion
* Fixed occasional reboot issues on some TP-Link WDR3600 and WDR4300 devices
```

2024-01-21 20:49 UTC, skorpy2009 approved these changes

2024-01-22 08:01 UTC, maurerle approved these changes

2024-01-23 09:59 UTC, grische approved these changes

2024-01-23 19:35 UTC, neocturne approved these changes

2024-01-23 21:30 UTC, merged