treewide: Update main name
freifunk-gluon/gluon pull request #3282
Opened 2024-06-13 17:56 UTC by neocturne

Following the rename of master to main, update everything that references the branch.

2024-06-13 18:02 UTC, mweinelt approved these changes

2024-06-13 18:25 UTC, AiyionPrime requested changes
Looks very well.
Minor nitpick.

2024-06-13 18:25 UTC, AiyionPrime commented on CONTRIBUTING.md
>  ------------------------
```suggestion
----------------------
```

2024-06-13 18:39 UTC, neocturne commented on CONTRIBUTING.md
>  ------------------------
Thanks, fixed.

2024-06-13 18:58 UTC, AiyionPrime approved these changes

2024-06-14 14:56 UTC, blocktrron approved these changes

2024-06-14 14:56 UTC, merged