Adding Support for Xiaomi Mi Router 4a Gigabit Edition v2 in Target ramips-mt7621
freifunk-gluon/gluon pull request #3293
Opened 2024-06-25 20:09 UTC by ChristianMiddendorf

- [x] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [x] Other: <First: Set Password for WLAN and System in Original Web interface. Second: Install Exploit as described at OpenWRT, Third: Copy sysupgrade image to /tmp via FTP, Forth: Open Telnet Session to go to /tmp directory to call mtd -e OS1 -r write name-of-your-sysupgrade-image.bin OS1  >
https://openwrt.org/inbox/toh/xiaomi/xiaomi_mi_router_4a_gigabit_edition#notes_on_firmware_exploit_procedure
- [x] Must support upgrade mechanism
  - [x] Must have working sysupgrade
    - [x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [ ] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
xiaomi-mi-router-4a-gigabit-edition-v2
- [x] Reset/WPS/... button must return device into config mode
- [x] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
    - if there are multiple ports but no WAN port:
      - the PoE input should be WAN, all other ports LAN
      - otherwise the first port should be declared as WAN, all other ports LAN
- Wireless network (if applicable)
  - [x] Association with AP must be possible on all radios
  - [x] Association with 802.11s mesh must work on all radios 
  - [x] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [x] Lit while the device is on
    - [x] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [ ] Should map to their respective radio
    - [ ] Should show activity
  - Switch port LEDs
    - [ ] Should map to their respective port (or switch, if only one led present) 
    - [ ] Should show link state and activity
- Outdoor devices only:
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
- Cellular devices only:
  - [ ] Added board name to `is_cellular_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
  - [ ] Added board name with modem setup function `setup_ncm_qmi` to `package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular`
- Docs:
  - [x] Added Device to `docs/user/supported_devices.rst`

2024-06-26 07:31 UTC, maurerle approved these changes
Why is 
> Gluon profile name matches autoupdater image name
not ticked?

As the device does not have radio/LAN LEDs, this looks good

2024-06-26 07:34 UTC, maurerle commented
You can write

closes #3291

into the PR description, to automatically close the issue, when merged.

2024-06-27 08:27 UTC, herbetom requested changes

2024-06-27 08:27 UTC, herbetom commented on targets/ramips-mt7621
> +
```suggestion
```

Minor nitpick: We've got two empty lines between diffrent Vendors but only one line between devices of the same vendor.

2024-06-27 08:27 UTC, herbetom commented on targets/ramips-mt7621
> +
```suggestion
```

same, only one empty line should suffice

2024-07-01 20:49 UTC, herbetom approved these changes
Ideally there should be only a single commit with a properly formated commit message. But in this case i thinks it's fine if whoever merges it simply does a "Squash and Merge".

Otherwise it looks okay. :+1:

2024-07-01 21:23 UTC, merged