Triband radio support
freifunk-gluon/gluon pull request #3357
Opened 2024-10-14 13:53 UTC by maurerle

I'd like to reopen the changes from #1666 to make way to support #1661

This works quite well and exposes the three wifis correctly on the status-page:

![image](https://github.com/user-attachments/assets/b8e9908d-f1a6-4428-86f8-e8f4b78469be)

radio0, 5GHz, 144 (client wifi)
radio1, 2.4GHz, 11 (client + mesh)
radio2, 5GHz, 44 (mesh)

and also the config mode shows the expected default config for such devices:
![image](https://github.com/user-attachments/assets/3ff85384-bec8-4e8e-ba2b-6fa09c372c16)

We might want to:

- [x] grey out the mesh network operation if a radio does only support DFS channels (removed, as the site api does not directly support disabling items)
- [ ] adjust config to detect how wifis should be distributed best across the channels (similar to how it is done here https://github.com/freifunk-gluon/gluon/blob/fc25b4940a7da61e4a60292324a3e2615122d810/package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless#L15 )
- [ ] move whole wireless configuration in uci to `gluon.wireless` in the future (far out of scope here)

This is currently focusing on having two 5GHz bands, where at least one does not support all channels.

---

This blocks the following PRs:

- #2769
- #3418

2024-10-14 14:25 UTC, herbetom commented
I think the mac address problem is as of now unresolved? https://github.com/freifunk-gluon/gluon/pull/1666#issuecomment-1232273562

2024-10-14 14:54 UTC, T-X commented
Would love to see the triband support! Devices with potential triband support and Gluon support I'm aware of: Plasmacloud PA2200 and the LibreRouter. Any other devices people would look forward to for triband support? Also, I guess this was untested with 6GHz so far? (I'd be looking forward to the Banana Pi BPI-R4, for instance, seems to have a dedicated phy for 6GHz for the WiFi7 iPA NIC module)

2024-10-14 15:01 UTC, maurerle commented
I think @Djfe  gave a quite extensive list of affected devices in https://github.com/freifunk-gluon/gluon/issues/1661#issuecomment-1441244292

For now, this does not include 6GHz. I have some ideas to add counters to the 6g band as well, but this would create to much noise and untested code (and I am not to familiar with 6GHz frequencies) , so I think we should do this one at a time.

From the list of open todos, I think I can handle the first two eventually, but would definitely need help for a complete overhaul (I think this way stopping the old PR mainly?). If there is someone willing to draft something where I can built on, improve and test, I would be very happy :)

2024-12-10 22:08 UTC, maurerle commented
There are concerns here regarding the probability of collision due to the reservation of the additional MAC addresses.
Steps to improve this are:

1. in batman-adv the mac address should be independent - should be checked: https://git.open-mesh.org/batman-adv.git/commit/5317331775c316
2. reconsider the assignment of mac addresses to avoid collisions
3. if we reserve more mac-addresses we have to see whether how we use them
@neocturne 

Regarding the assignment of the interfaces:
We don't need to solve this dynamically - write down the existing cases once (see all the triband devices)
and see if we have a solution for all cases.

2024-12-14 14:10 UTC, maurerle commented
If the last mac-address byte was `254` then the next mac-addresses could overflow leading to something like:

`root@ffac-lothringer-flomi:~# lua -e 'print(require("gluon.util").generate_mac(9))'`
`0a:a2:8d:fb:f9:102`

One way to solve this is to zero more than 3 bits in
`m6 = bit.band(m6, 0xF8) -- zero the last three bits (space needed for counting)`
or just let the counter overflow.

See: https://github.com/freifunk-gluon/gluon/pull/3357/commits/af539fc577f691984c08d984b81de685032bac3c

I think one can even remove the `m6 = bit.band(m6, 0xF8)` part now? @neocturne

2024-12-22 19:45 UTC, maurerle commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +local has_client_radio = false
should be renamed to `has_client_only_radio` as this checks for a radio which can not be used for mesh

2024-12-22 20:06 UTC, maurerle commented
Looking at the device list provided by @djfe in https://github.com/freifunk-gluon/gluon/issues/1661#issuecomment-1441244292 I came to two possible operation modes:

a - there is 1 radio which supports only a subset of the channels while the other radio supports all unsupported channels (or more)
b - there are 2 radios with the same support channels, eventually with the same quality, eventually one radio would be preferred (though I neither know how to find the preference or set a preference to use the "better" one for mesh vs client :shrug: )

 Devices                               | 2.4GHz | 5GHz                  | Preferred Usage
---------------------------------------|--------|-----------------------|-----------------
 OpenMesh A62                          | 1      | 2                     | a
 [Plasma Cloud PA2200](https://openwrt.org/toh/hwdata/plasma_cloud/plasma_cloud_pa2200)                   | 1      | 2                     | a
 [AVM Fritz!Repeater 3000](https://github.com/freifunk-gluon/gluon/pull/3057) and 6000      | 1      | 2                     | a
 AVM Fritz!Box 4060                    | -      | no support            |
 LibreRouter v1                        | 1      | 2 (both working)      | b
 Linksys [MR8300](https://github.com/freifunk-gluon/gluon/pull/2769)/EA8300, (EA7500)       | 1      | 2                     | a
[ Xiaomi AX3600](https://openwrt.org/toh/xiaomi/ax3600)                         | 1      | 1+ 1not really usable | ?
 [Xiaomi AX9000](https://openwrt.org/toh/xiaomi/ax9000)                         | 1      | 2 (both working?)     | b
[ GL.iNet GL-B2200](https://openwrt.org/toh/gl.inet/gl-b2200)                      | 1      | 2 (both working?)     | b
 Linksys Velop (WHW01 v1 and [WHW03 v2](https://openwrt.org/toh/linksys/whw03_v2)) | 1      | 2 (different channel) | a
 Meraki MR33                           | 2      | 2                     | ?

This PR should work for the usage of a and b by default, while the user can configure different behavior.

TODO:

- [ ] test on different three-radio routers
- [ ] disable option from `gluon-web-wifi-config` to configure a wifi on an unsupported channel if `wireless.supports_channel(radio, config.channel())` is False

2025-01-08 22:22 UTC, Djfe commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +	-- disable setting mesh iface setting if radio does not support configured mesh channel
Just a suggestion to use positive wording here. Instead of double negative.

> -- only show mesh iface setting if said radio supports the configured mesh channel

2025-01-09 00:30 UTC, Djfe commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
maybe add a code comment, what this is supposed to achieve

> -- Assign mesh radio and client radio to separate 5GHz radios if at least two exist and one of them doesn't support mesh channels. Let the one(s) that doesn't support mesh channels run as client radio and run mesh radio on all remaining 5GHz radios. 5GHz radios will have one WiFi interface each in this case.

2025-03-11 19:19 UTC, neocturne requested changes

2025-03-11 19:19 UTC, neocturne commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +	m6 = math.fmod(m6 + i, 256)   -- add virtual interface id
This commit needs to be squashed into the previous.

Instead of `fmod`, it's better to use `m6 = bit.band(m6 + i, 0xFF)` for consistency with the rest of the code.

2025-03-11 19:19 UTC, neocturne commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +if not sysconfig.gluon_version and has_client_radio then
Checks for `sysconfig.gluon_version` are almost always wrong. It's better to delete and recreate as much config as possible on each reconfigure instead of trying to handle the first run differently.

All new config that needs to persist should be stored in `/etc/config/gluon` - eventually I'd like to make that the only file that is preserved on upgrades at all.

2025-03-11 19:19 UTC, neocturne commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +local has_client_radio = false
The rationale behind `has_client_radio` could use an explanatory comment.

2025-03-11 19:19 UTC, neocturne commented on package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
> +	if radio.band == '5g' and (is_outdoor() or not util.supports_channel(radio, config.channel())) then
I'm wondering if something like the following would make sense:
```lua
	if (radio.band == '5g' and is_outdoor()) or not util.supports_channel(radio, config.channel()) then
```
But I guess having radios for distinct ranges isn't really a thing for 2.4GHz...

2025-03-11 19:19 UTC, neocturne commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +	if not wireless.supports_channel(radio, config.channel()) then
Another commit that needs to be squashed. Always squash fixes, so the resulting commits make sense by themselves for review.

2025-03-11 19:19 UTC, neocturne commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +local has_client_only_radio = false
This commit appears to include an unrelated variable rename.

2025-03-11 19:19 UTC, neocturne commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
Maybe add a notice that it's unsupported instead of just removing the checkbox?

2025-03-14 17:22 UTC, maurerle commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +	m6 = math.fmod(m6 + i, 256)   -- add virtual interface id
Thanks!
Just a question: why is it needed to "zero the last three bits (space needed for counting)"?
I think this is just convenient as one knows which MAC is which, but it would not be required if I am not mistaken..?

2025-03-14 17:27 UTC, maurerle commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +	if not wireless.supports_channel(radio, config.channel()) then
I left the commits splitted, as parts were developed by blocktrron and I wanted to keep this state - but I squashed it now, for easier reviewing

2025-03-14 17:53 UTC, herbetom commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +	if not wireless.supports_channel(radio, config.channel()) then
In that case "co-authored-by" should be added to the commits this affects.

2025-03-14 19:31 UTC, neocturne commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +	m6 = math.fmod(m6 + i, 256)   -- add virtual interface id
For some radios, all VIFs need to use MAC addresses that only differ in the last 3 bits. This was achieved by setting the last 3 bits to 0 and counting up for up to 8 addresses.

2025-03-15 11:03 UTC, maurerle commented on package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
> +	if radio.band == '5g' and (is_outdoor() or not util.supports_channel(radio, config.channel())) then
Yes, I think that your suggestion still makes sense - I adapted it.

2025-03-15 11:14 UTC, maurerle commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +	m6 = math.fmod(m6 + i, 256)   -- add virtual interface id
Thanks, then I will leave it as it is now

2025-03-19 23:14 UTC, neocturne commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +if not sysconfig.gluon_version and has_client_radio then
I'd add an optional 3rd argument to `is_disabled()` to extend the logic in the case where the UCI section does not exist yet.

2025-03-19 23:25 UTC, neocturne commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +-- A: ibss2
We don't support IBSS, should be owe2

I'm also pondering if we should change `generate_mac` to take 2 arguments - a radio index + an address offset 0..3, where each radio index would result in a different hash seed (and the non-WLAN callers of `generate_mac` would pass 0 or 1 as the radio index)

2025-04-01 22:14 UTC, blocktrron commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +-- A: ibss2
I think this was going into the direction of where i did propose this years ago.

I have another thought - In addition to calling this by indexes which effectively translate to an offset in the assigned block of n (8?) addresses, how about we use named indexes?

This way, we can track all handed out addresses by name. This has the upside of allowing 3rd party community packages to obtain unique per-radio addresses.

2025-04-15 19:35 UTC, maurerle commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
I don't quite now how this should be done with our config mode. So this is still open

2025-04-15 22:26 UTC, neocturne commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
See https://github.com/freifunk-gluon/gluon/blob/main/package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua#L29-L35 for a conditionally displayed warning. This refers to the template in gluon-web-model/files/lib/gluon/web/view/model/warning.html - a similar template could be added for a "notice".

2025-04-16 05:25 UTC, T-X commented
One point I briefly mentioned during the last meetup yesterday:

Especially if we were using higher channel bandwidths on 5GHz at some point and with BATMAN V, we might be able to achieve higher, overall throughput with mesh enabled on the secondary 5GHz, too. As then a) BATMAN V with its throughput metric would likely/often prefer just meshing on 5GHz, not 2.4GHz. And b) would be using interface alternating between the two 5GHz interfaces to avoid the half-duplex nature of WLAN: https://www.open-mesh.org/projects/batman-adv/wiki/Multi-link-optimize#Interface-alternating

But as noted during the meetup, it might maybe be difficult to agree on the exact channel for the secondary 5GHz wifi. Having this configurable in the config mode seems great for now, though.

2025-04-16 07:05 UTC, Djfe commented
@T-X suggestion to have mesh interfaces on both 5GHz phys for batman-adv interface alternating when DFS allows for the secondary channels to be used, is intriguing and a nice afterthought how to continue this work after this was merged.
(I wrote with T-X over IRC just now to clarify how his statement is meant)

It would increase throughput when no radar etc. is present and allow forwarding mesh traffic in a full duplex manner over 5GHz only.

2025-06-23 23:03 UTC, maurerle commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
Thanks, then it would just look like this:
![image](https://github.com/user-attachments/assets/16a53614-a179-4a57-a4b5-4ae771189000)

What do you think of it @neocturne ? :)

2025-06-23 23:34 UTC, Djfe commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
Two alternative phrasings:
- This WLAN radio doesn't support the channel range required for meshing.
- This WLAN radio doesn't support the channel selected by your community for meshing.

I like that your variant is shorter but it might leave people less knowledgeable people a bit puzzled. (yes, this is in advanced settings after all. but still)

2025-06-23 23:45 UTC, maurerle commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +		end
I added a notice as you suggested now. I think this looks better:

![image](https://github.com/user-attachments/assets/a063686d-ecb5-4bbc-8cd9-b754ec88e1f5)

2025-06-23 23:56 UTC, maurerle commented on package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
> +if not sysconfig.gluon_version and has_client_radio then
Thank you! I fixed this by checking 

`if is_disabled_wireless(radio_name) == nil then` for every radio instead.
Seemed easier in this case :)

2025-06-24 08:29 UTC, maurerle commented
I tested this. It works as expected.
Some strings should maybe adjusted, but I don't have strong feelings on that.
@neocturne can you please take another look?

2025-06-26 12:49 UTC, AiyionPrime requested changes
@lemoer and I took a brief look at this.
In general this looks great.

Nitpicks aside, the only thing I cannot wrap my head around, are the implications regarding mac overflow cutoffs due to the overflow prevention `band(..., 0xff)`.

Therefore the discussion I'm most interested in rn is this one _posted by @neocturne in https://github.com/freifunk-gluon/gluon/pull/3357#discussion_r2004467601_.

2025-06-26 12:49 UTC, AiyionPrime commented on package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
> +			content = translate("Mesh deactivated due to unsupported channel"),
```suggestion
			content = translate("Mesh deactivated due to unsupported channel"),
```
```suggestion
			content = translate("Mesh deactivated due to unsupported channel."),
```

Just a nitpick; the other box texts ends in a dot :)

2025-07-21 19:06 UTC, maurerle commented on package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
> +-- A: ibss2
This is now fixed with #3539 - @neocturne can you take another look please?

2025-07-22 11:23 UTC, neocturne requested changes

2025-07-22 11:23 UTC, neocturne commented on package/gluon-web-wifi-config/i18n/de.po
> +msgstr "Der ausgewählte Mesh-Kanal wird von diesem WLAN radio nicht unterstützt."
Hmm, "radio" is not very common in this context in German. "WLAN-Gerät"?

2025-07-22 11:26 UTC, neocturne commented
Hmm, I guess recovering the user intent regarding enabling or disabling certain radios/VIFs becomes more difficult with this PR. One idea I've been thinking of for some time - in particular in the context of moving user intent to `/etc/config/gluon` - is to remove the option to configure individual radios through Gluon's UI, instead just storing "client on 2.4GHz", "mesh on "2.4GHz" etc. and letting the config scripts deal with the details.

2025-07-22 12:24 UTC, Djfe commented
honestly that's a good point and it probably should be done. but since this only affects devices with radios with limited channel range: for now we could move that discussion to a follow up PR.
Sure that's not ideal and it could lead to said PR to not being merged before the release.
But it's out of scope and makes the discussion more convoluted, no?
I really feel like keeping the user's intent saved is important though, please don't get me wrong. But for now the user doesn't even have the option in config mode so it pretty much is the user's intent. Sure this can be enhanced later on and for old installations the intent would stay the same and transferred into the new entries in '/etc/config/gluon'

Offtopic:
Why I feel that it makes sense to brainstorm @neocturne's idea further before it can take shape:
- How do we want to structure the new wireless config option within gluon so it fits a schema for further ideas on the table?
- How do we communicate to ssh users that one wIf currently cannot be enabled? It feels weird/like a bug when there are two disabled options for the same style interface and gluon-reconfigure doesn't transfer the disabled=0 from gluon to wireless. Or is there only one general option per band and gluon assigns it to one radio and disables it for the other one on the same band? That could work actually. Though in the future we might want to have the option to assign mesh radio to both radios on the same band even though one is a non-standard frequency (for a local installation)

2025-07-22 12:51 UTC, maurerle commented
@neocturne
> I guess recovering the user intent regarding enabling or disabling certain radios/VIFs becomes more difficult with this PR.
Why do you think so? This basically sets a config for the third radio, but would respect user changes once set up?

Would you consider solving config movement to a gluon section as  outlined in #3550 mandatory for this PR or as something we can still see separately?

2025-07-22 13:13 UTC, neocturne commented
> @neocturne
> 
> > I guess recovering the user intent regarding enabling or disabling certain radios/VIFs becomes more difficult with this PR.
> 
> Why do you think so? This basically sets a config for the third radio, but would respect user changes once set up?

Hmm true, the code preserves the `disabled` values. But I wonder what would happen during a channel change - due to upgrade or domain change - that would change `has_client_only_radio` from true to false? I think we would end up with the other client radio disabled, but that does not represent user intent.

2025-07-22 14:08 UTC, maurerle commented
@neocturne 
I introduced `if is_disabled_wireless(radio_name) == nil then` instead of checking for `sysconfig.gluon_version`

So disabling of a client wifi is only done, if the config does not yet exist.
See also this comment/thread: https://github.com/freifunk-gluon/gluon/pull/3357#discussion_r2162705572

2025-07-22 14:23 UTC, neocturne commented
> @neocturne I introduced `if is_disabled_wireless(radio_name) == nil then` instead of checking for `sysconfig.gluon_version`
> 
> So disabling of a client wifi is only done, if the config for this radio does not yet exist. See also this comment/thread: [#3357 (comment)](https://github.com/freifunk-gluon/gluon/pull/3357#discussion_r2162705572)

Exactly! And it will remain disabled when the mesh channel changes, even if a configuration from scratch would enable it. In this case, it is currently impossible to recover the user intent because the information whether the setting was done by the script or the user is simply not available.

2025-07-22 14:36 UTC, maurerle commented
True, thanks.

Though in reality I found no community which has different channels in their domain.conf  - all did have it in the `site.conf`.
And I would not expect a community to have a configured wifi5 mesh channel above 100 leading to such problems..
Or are there other scenarios in which the mesh channel could suddenly not work?

2025-07-22 15:13 UTC, herbetom commented
> Though in reality I found no community which has different channels in their domain.conf - all did have it in the site.conf.

When looking at a multitude of sites communities do define channel info inside their domains. Sometimes it's redundant, sometimes they probably changed channels during a scheduled domain switch but didn't remove the old domain and sometimes there might be other reasons:

<details>

<summary>Show grep</summary>

```bash
$ git clone https://github.com/herbetom/ff-sites.git --recurse-submodules
$ grep -ri "channel =" | grep domains
site-ffrgb/domains/ffrgb_uml.conf:    channel = 1,
site-ffrgb/domains/ffrgb_uml.conf:    channel = 44,
site-ffrgb/domains/ffrgb_cty.conf:    channel = 1,
site-ffrgb/domains/ffrgb_cty.conf:    channel = 44,
site-ffrgb/domains/ffrgb_tst.conf:    channel = 1,
site-ffrgb/domains/ffrgb_tst.conf:    channel = 44,
site-ffs/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 1,
site-ffs/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 44,
site-fffl/domains/Niebuell_v1.conf:        channel = 1,
site-fffl/domains/Niebuell_v1.conf:        channel = 44,
site-fffl/domains/Flensburg_v1.conf:        channel = 1,
site-fffl/domains/Flensburg_v1.conf:        channel = 44,
site-ff3l/domains/ssww.conf:		channel = 1,
site-ff3l/domains/ssww.conf:		channel = 44,
site-ff3l/domains/ffng.conf:		channel = 1,
site-ff3l/domains/ffng.conf:		channel = 44,
site-ff3l/domains/wiese.conf:		channel = 1,
site-ff3l/domains/wiese.conf:		channel = 44,
site-ff3l/domains/sswo.conf:		channel = 1,
site-ff3l/domains/sswo.conf:		channel = 44,
site-ff3l/domains/ref.conf:		channel = 1,
site-ff3l/domains/ref.conf:		channel = 44,
site-ff3l/domains/nalb.conf:		channel = 1,
site-ff3l/domains/nalb.conf:		channel = 44,
site-ff3l/domains/swb.conf:		channel = 1,
site-ff3l/domains/swb.conf:		channel = 44,
site-ff3l/domains/saek.conf:		channel = 1,
site-ff3l/domains/saek.conf:		channel = 44,
site-ff3l/domains/rhf.conf:		channel = 1,
site-ff3l/domains/rhf.conf:		channel = 44,
site-ff3l/domains/loe.conf:		channel = 1,
site-ff3l/domains/loe.conf:		channel = 44,
site-ff3l/domains/3land.conf:		channel = 1,
site-ff3l/domains/3land.conf:		channel = 44,
site-ff3l/domains/hotz.conf:		channel = 1,
site-ff3l/domains/hotz.conf:		channel = 44,
site-ff3l/domains/ffem.conf:		channel = 1,
site-ff3l/domains/ffem.conf:		channel = 44,
site-ff3l/domains/bh.conf:		channel = 1,
site-ff3l/domains/bh.conf:		channel = 44,
site-ff3l/domains/default.conf:		channel = 1,
site-ff3l/domains/default.conf:		channel = 44,
site-ff3l/domains/fftut.conf:		channel = 1,
site-ff3l/domains/fftut.conf:		channel = 44,
site-ff3l/domains/fffr.conf:		channel = 1,
site-ff3l/domains/fffr.conf:		channel = 44,
site-ff3l/domains/wtk.conf:		channel = 1,
site-ff3l/domains/wtk.conf:		channel = 44,
site-ffc/domains/neukirchen.conf:            channel = 1,
site-ffc/domains/neukirchen.conf:            channel = 36,
site-ffc/domains/zwickau.conf:            channel = 11,
site-ffc/domains/zwickau.conf:            channel = 36,
site-ffc/domains/hartmannsdorf.conf:            channel = 1,
site-ffc/domains/hartmannsdorf.conf:            channel = 36,
site-ffc/domains/penig.conf:            channel = 1,
site-ffc/domains/penig.conf:            channel = 36,
site-ffc/domains/eventnet.conf:            channel = 1,
site-ffc/domains/eventnet.conf:            channel = 36,
site-ffc/domains/hainichen.conf:            channel = 1,
site-ffc/domains/hainichen.conf:            channel = 36,
site-ffc/domains/frankenberg.conf:            channel = 1,
site-ffc/domains/frankenberg.conf:            channel = 36,
site-ffc/domains/floeha.conf:            channel = 11,
site-ffc/domains/floeha.conf:            channel = 36,
site-ffc/domains/umland.conf:            channel = 1,
site-ffc/domains/umland.conf:            channel = 36,
site-ffc/domains/chemnitz.conf:            channel = 11,
site-ffc/domains/chemnitz.conf:            channel = 36,
site-ffc/domains/mittweida.conf:            channel = 1,
site-ffc/domains/mittweida.conf:            channel = 36,
site-ffhl/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 1,
site-ffhl/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 44,
site-ffm/domains/ffdon_mitte.conf:    channel = 1,
site-ffm/domains/ffdon_nordwest.conf:    channel = 1,
site-ffm/domains/ffdon_sued.conf:    channel = 1,
site-ffef/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 1,
site-ffef/gluon/docs/multidomain-site-example/domains/alpha_centauri.conf:      channel = 44,
site-ffef/domains/ffil_v1.conf:		channel = 6,
site-ffef/domains/ffil_v1.conf:		channel = 44,
site-ffef/domains/ffwsee_v1.conf:		channel = 1,
site-ffef/domains/ffwsee_v1.conf:		channel = 44,
site-ffef/domains/ffthw_v1.conf:		channel = 1,
site-ffef/domains/ffthw_v1.conf:		channel = 44,
site-ffef/domains/ffen_v1.conf:		channel = 1,
site-ffef/domains/ffen_v1.conf:		channel = 44,
site-ffef/domains/ffef_v1.conf:		channel = 1,
site-ffef/domains/ffef_v1.conf:		channel = 44,
site-ffef/domains/ffgth_v1.conf:		channel = 1,
site-ffef/domains/ffgth_v1.conf:		channel = 44,
site-fftr/domains/fftr_l2tp.conf:		channel = 1,
site-fftr/domains/fftr_l2tp.conf:		channel = 44,
site-fftr/domains/fftr.conf:		channel = 1,
site-fftr/domains/fftr.conf:		channel = 44,
site-ffv/domains/ffv_tri.conf:		channel = 11,
site-ffv/domains/ffv_tri.conf:		channel = 36,
site-ffv/domains/ffv_sbg.conf:		channel = 11,
site-ffv/domains/ffv_sbg.conf:		channel = 36,
site-ffv/domains/ffv_b.conf:		channel = 11,
site-ffv/domains/ffv_b.conf:		channel = 36,
site-ffv/domains/ffv_boe.conf:		channel = 11,
site-ffv/domains/ffv_boe.conf:		channel = 36,
site-ffv/domains/ffv_le.conf:		channel = 11,
site-ffv/domains/ffv_le.conf:		channel = 36,
site-ffv/domains/fferz.conf:		channel = 11,
site-ffv/domains/fferz.conf:		channel = 36,
site-ffv/domains/ffv_oel.conf:		channel = 11,
site-ffv/domains/ffv_oel.conf:		channel = 36,
site-ffv/domains/ffv_mtl.conf:		channel = 11,
site-ffv/domains/ffv_mtl.conf:		channel = 36,
site-ffv/domains/ffv_wei.conf:		channel = 11,
site-ffv/domains/ffv_wei.conf:		channel = 36,
site-ffv/domains/ffv_mh.conf:		channel = 11,
site-ffv/domains/ffv_mh.conf:		channel = 36,
site-ffv/domains/ffv_mkn.conf:		channel = 11,
site-ffv/domains/ffv_mkn.conf:		channel = 36,
site-ffv/domains/ffv_k.conf:		channel = 11,
site-ffv/domains/ffv_k.conf:		channel = 36,
site-ffv/domains/ffv_gb.conf:		channel = 11,
site-ffv/domains/ffv_gb.conf:		channel = 36,
site-ffv/domains/ffv_t.conf:		channel = 11,
site-ffv/domains/ffv_t.conf:		channel = 36,
site-ffv/domains/ffv_els.conf:		channel = 11,
site-ffv/domains/ffv_els.conf:		channel = 36,
site-ffv/domains/ffv_n.conf:		channel = 11,
site-ffv/domains/ffv_n.conf:		channel = 36,
site-ffv/domains/ffv_eic.conf:		channel = 11,
site-ffv/domains/ffv_eic.conf:		channel = 36,
site-ffv/domains/ffv_hdg.conf:		channel = 11,
site-ffv/domains/ffv_hdg.conf:		channel = 36,
site-ffv/domains/ffv_rc.conf:		channel = 11,
site-ffv/domains/ffv_rc.conf:		channel = 36,
site-ffv/domains/ffv_s.conf:		channel = 11,
site-ffv/domains/ffv_s.conf:		channel = 36,
site-ffv/domains/ffv_wer.conf:		channel = 11,
site-ffv/domains/ffv_wer.conf:		channel = 36,
site-ffv/domains/ffv_a.conf:		channel = 11,
site-ffv/domains/ffv_a.conf:		channel = 36,
site-ffv/domains/ffv_tr.conf:		channel = 11,
site-ffv/domains/ffv_tr.conf:		channel = 36,
site-ffv/domains/ffv_bb.conf:		channel = 11,
site-ffv/domains/ffv_bb.conf:		channel = 36,
site-ffv/domains/ffv_l.conf:		channel = 11,
site-ffv/domains/ffv_l.conf:		channel = 36,
site-ffv/domains/ffv_ell.conf:		channel = 11,
site-ffv/domains/ffv_ell.conf:		channel = 36,
site-ffv/domains/ffv_rbh.conf:		channel = 11,
site-ffv/domains/ffv_rbh.conf:		channel = 36,
site-ffv/domains/ffv_nst.conf:		channel = 11,
site-ffv/domains/ffv_nst.conf:		channel = 36,
site-ffv/domains/ffv_nsz.conf:		channel = 11,
site-ffv/domains/ffv_nsz.conf:		channel =  [...]

2025-07-22 23:20 UTC, rotanid commented
> Though in reality I found no community which has different channels in their domain.conf - all did have it in the `site.conf`. 

we have one domain with a different channel.
such things can happen if communities merge and/or decide to use the same firmware base.

2025-07-23 09:48 UTC, AiyionPrime commented
We talked about it two weeks back, our community intends to use it as experimental domains.
Different channel, different SSID, (different Mesh ID for good measure).

2025-07-25 05:53 UTC, maurerle commented
@herbetom thanks for doing a thorough check, I should not have generalized from a handful, sorry.

> And I would not expect a community to have a configured wifi5 mesh channel above 100 leading to such problems..
Or are there other scenarios in which the mesh channel could suddenly not work?

I still don't see where this would be an issue.
The devices have a client-only Wi-Fi because they only support outdoor channels. Therefore, this would only be an issue when switching to meshing on outdoor channels, which is also not supported with the outdoor role.

Though I see that we want to spare ourselves from doing migrations of such devices where we can't know what the original user intent is.
In that case, this PR is blocked until we rebuild the wireless config from /etc/config/gluon (#3550)

2025-09-07 11:08 UTC, maurerle commented
superseded by #3563

2025-09-07 11:08 UTC, closed without merging