base: update to OpenWrt 24.10
freifunk-gluon/gluon pull request #3370
Opened 2024-11-05 18:53 UTC by blocktrron

This PR switches Gluon to the latest OpenWrt 24.10 release. 

With this release, support or 2 devices is dropped due to them not fulfilling the minimum flash space requirements anymore.

2024-11-05 18:53 UTC, blocktrron commented
Question is whether we want to do a Wrap-Up release on 23.05 with everything up to this point and switch afterwards. We did this in the past and i think of this as a good way to create a stable release EOY.

2024-11-08 01:56 UTC, rotanid commented
> Question is whether we want to do a Wrap-Up release on 23.05 with everything up to this point and switch afterwards. We did this in the past and i think of this as a good way to create a stable release EOY.

thank you for your work and i would agree with doing a Wrap-up v2024.1 Release.

2024-11-12 21:46 UTC, rotanid commented
removing the Edgerouter X might be obsolete after that backport:
https://github.com/openwrt/openwrt/pull/16893

2024-11-12 22:35 UTC, blocktrron commented
I don't have said device, can't say anything about this backport.

2024-11-14 16:42 UTC, neocturne requested changes

2024-11-14 16:42 UTC, neocturne commented on contrib/docker/Dockerfile
> +    python3-setuptools \
This adds a lot more packages than are mentioned in the commit message.

2024-11-14 16:42 UTC, neocturne commented on targets/mediatek-mt7622
> -device('xiaomi-redmi-router-ax6s', 'xiaomi_redmi-router-ax6s', {
Doc update?

2024-11-14 16:42 UTC, neocturne commented on targets/ramips-mt7621
> -device('ubiquiti-edgerouter-x-sfp', 'ubnt_edgerouter-x-sfp', {
Doc updates?

2024-11-14 16:42 UTC, neocturne commented on scripts/copy_output.lua
> +	lib.exec {'rm', '-rf', 'openwrt/bin/targets/'..bindir..'/packages/tmp\0'}
The `\0` (`*` wildcard) seems unnecessary, or can the directory name vary?
```suggestion
	lib.exec {'rm', '-rf', 'openwrt/bin/targets/'..bindir..'/packages/tmp'}
```

2024-12-06 20:53 UTC, autinerd commented
We from Freifunk Stuttgart are currently creating an experimental build based on this PR, but with OpenWrt 24.10-rc2 and re-added EdgeRouter X support, we will try to test if the backport works.

2024-12-09 14:18 UTC, merged